format = """
[░▒▓█](#9A348E)\
$username[$sudo](bg:#9A348E)\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[ ](fg:#06969A)\
"""
right_format = """
$character\
$cmd_duration\
[](fg:#33658A bg:yellow)\
($battery)\
$time\
[█▓▒░](fg:#33658A)\
"""
# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3336
truncation_symbol = "…/"

[character]
format = "$symbol"
success_symbol = "[](fg:green)[](fg:yellow bg:green)"
error_symbol = "[](fg:red)[ ✘ ](fg:white bg:red)[](fg:yellow bg:red)"
vimcmd_symbol = "[](fg:green)[ NORMAL ](fg:white bg:green)[](fg:yellow bg:green)"
vimcmd_visual_symbol = "[](fg:#0362FC)[ VISUAL ](fg:white bg:#0362FC)"
vimcmd_replace_symbol = "[](fg:#0362FC)[ REPLACE ](fg:white bg:#0362FC)"
vimcmd_replace_one_symbol = "[](fg:#0362FC)[ REPLACE ](fg:white bg:#0362FC)"

[cmd_duration]
min_time = 2000
show_milliseconds = true
format = "[  $duration ](fg:white bg:yellow)"

[sudo]
format = "[ as $symbol ]($style)"
disabled = true
allow_windows = true
symbol = "聯 "
style = "fg:blue bg:#9A348E"

[battery]
format = "[$symbol$percentage]($style bg:#33658a)"

[[battery.display]]
threshold = 100
style = "bold green"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 30
style = "bold red"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[  $time ]($style)'
